### ISSUE TITLE
You can use the bot in DMs outside a server

### ISSUE THREAD

**Issue by jzimr** [multicus/RSS_Notification_Bot_and_API#3]
Don't think we should allow this?

**Comment by newtpuandre** [comment]
ref issue comment #4 . If dms all together should be disallowed i can make a easy fix, but if we want to allow certain commands i most likely need to rewrite some of the handler functions.

**Comment by jzimr** [comment]
You can now only use the "!commands" command in DMs. Fixed in commit [db6e61f](https://github.com/multicus/RSS_Notification_Bot_and_API/commit/f351bd394c493acc5e58a3229cb9b27a93846399)
