### ISSUE TITLE
Bot crashes when certain commands (e.g. !rssnewkey) are typed in DM

### ISSUE THREAD

**Issue by jzimr** [multicus/RSS_Notification_Bot_and_API#4]

**Comment by newtpuandre** [comment]
I guess the !rssnewkey command are supposed to only be functional in DMs, not in channels?

**Comment by jzimr** [comment]
Fixed in commit [db6e61f](https://github.com/multicus/RSS_Notification_Bot_and_API/commit/f351bd394c493acc5e58a3229cb9b27a93846399)
